### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by NidusPrime123** [NidusPrime123/PokemonPartyBuilder#2]
There are white gaps around the web's UI. Please fix it
![issue](https://user-images.githubusercontent.com/28347010/201611278-45f2b4d0-3ccf-4add-a7b7-4c2d43192a85.png)

**Comment by haunuongphomai** [comment]
Let me work on this issue

**Comment by NidusPrime123** [comment]
@haunuongphomai go ahead. Make sure to follow the steps I listed out in the README.md file

**Comment by haunuongphomai** [comment]
I already fix your issue
![image](https://user-images.githubusercontent.com/66356445/201643398-0d80644b-b719-4f3d-abd4-589646e838e3.png)

**Comment by NidusPrime123** [comment]
issue resolved
